[package]
name = "is_printable"
version = "0.1.2"
edition = "2024"
rust-version = "1.94.0"
description = "Determine whether a given text-based value is printable."
documentation = "https://docs.rs/is_printable"
readme = "README.md"
repository = "https://github.com/amab8901/is_printable"
license = "MIT OR Apache-2.0"
keywords = ["ascii", "char", "is_printable", "printable", "utf8"]

[dev-dependencies]
colored = "2.1.0"

[lints.clippy]
let_and_return = "allow"
missing_errors_doc = "allow"
missing_inline_inpublic_items = "allow"
missing_panics_doc = "allow"
mod_module_files = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
non_exhaustive_structs = "allow"
self_named_module_files = "allow"
similar_names = "allow"
std_instead_of_core = "allow"
too_many_arguments = "allow"

pedantic = { level = "warn", priority = -1 }
